### ISSUE TITLE
Compiled??

### ISSUE THREAD

**Issue by 1923812371283127398123712893126793** [IAMLEIIKUN/PisoWiFi-Hotspot-Android-App-with-Navigation-Drawer-Menu#1]
Can i get a compiled one

**Comment by IAMLEIIKUN** [comment]
Sorry but I don't understand. Can you please clarify it for me?

Thanks for visiting this project tho!

**Comment by 023948799e213e21b53eb83785356208** [comment]
> Sorry but I don't understand. Can you please clarify it for me?
> 
> Thanks for visiting this project tho!

im the alt but i just want an .apk one cause i dont have a pc to build apks in android studio

**Comment by IAMLEIIKUN** [comment]
> > Sorry but I don't understand. Can you please clarify it for me?
> > Thanks for visiting this project tho!
> 
> im the alt but i just want an .apk one cause i dont have a pc to build apks in android studio

You still cannot use this app since it requires you to connect to an specific wifi name. You will need to reconfigure it by decompiling it on android studio.

Bonus Tip: You can use a modded AIDE (android app) to decompile and recompile android studio projects.

**Comment by 023948799e213e21b53eb83785356208** [comment]
> > > Sorry but I don't understand. Can you please clarify it for me?
> > > Thanks for visiting this project tho!
> > 
> > 
> > im the alt but i just want an .apk one cause i dont have a pc to build apks in android studio
> 
> You still cannot use this app since it requires you to connect to an specific wifi name. You will need to reconfigure it by decompiling it on android studio.
> 
> Bonus Tip: You can use a modded AIDE (android app) to decompile and recompile android studio projects.

thanks for the tip

**Comment by IAMLEIIKUN** [comment]
You're welcome. Please, feel free to fork this repo. Thanks!
